/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smartdone_printlog_Log */

#ifndef _Included_com_smartdone_printlog_Log
#define _Included_com_smartdone_printlog_Log
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smartdone_printlog_Log
 * Method:    println_native
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_smartdone_printlog_Log_println_1native
  (JNIEnv *, jclass, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
